import os

files = {
    "requirements.txt": "fastapi==0.110.0\nuvicorn==0.27.1\nsqlalchemy==2.0.28\npydantic==2.6.3\npydantic-settings==2.2.1\n",
    "app/__init__.py": "",
    "app/main.py": "from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\nfrom app.core.config import settings\nfrom app.database.session import engine, Base\nimport app.models.all_models # Import models to ensure tables are created\n\nBase.metadata.create_all(bind=engine)\n\napp = FastAPI(\n    title=settings.PROJECT_NAME,\n    version='1.0.0',\n    description='Backend API for DecisionLedger TEC'\n)\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=settings.CORS_ORIGINS,\n    allow_credentials=True,\n    allow_methods=['*'],\n    allow_headers=['*'],\n)\n\n@app.get('/health')\ndef health_check():\n    return {'status': 'ok', 'project': settings.PROJECT_NAME}\n",
    "app/core/__init__.py": "",
    "app/core/config.py": "from pydantic_settings import BaseSettings\nfrom typing import List\n\nclass Settings(BaseSettings):\n    PROJECT_NAME: str = 'DecisionLedger TEC'\n    DATABASE_URL: str = 'sqlite:///./decisionledger.db'\n    CORS_ORIGINS: List[str] = ['*']\n    \n    class Config:\n        env_file = '.env'\n\nsettings = Settings()\n",
    "app/core/logger.py": "import logging\nimport sys\n\ndef get_logger(name: str):\n    logger = logging.getLogger(name)\n    logger.setLevel(logging.INFO)\n    \n    if not logger.handlers:\n        handler = logging.StreamHandler(sys.stdout)\n        handler.setLevel(logging.INFO)\n        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')\n        handler.setFormatter(formatter)\n        logger.addHandler(handler)\n        \n    return logger\n",
    "app/database/__init__.py": "",
    "app/database/session.py": "from sqlalchemy import create_engine\nfrom sqlalchemy.orm import declarative_base, sessionmaker\nfrom app.core.config import settings\n\nengine = create_engine(\n    settings.DATABASE_URL, connect_args={'check_same_thread': False}\n)\nSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)\n\nBase = declarative_base()\n\ndef get_db():\n    db = SessionLocal()\n    try:\n        yield db\n    finally:\n        db.close()\n",
    "app/models/__init__.py": "",
    "app/models/all_models.py": "from sqlalchemy import Column, String, Float, Integer, Boolean, DateTime, ForeignKey, Text\nfrom sqlalchemy.orm import relationship\nimport uuid\nfrom datetime import datetime\nfrom app.database.session import Base\n\ndef generate_uuid():\n    return str(uuid.uuid4())\n\nclass Transaction(Base):\n    __tablename__ = 'transactions'\n    \n    id = Column(String, primary_key=True, default=generate_uuid)\n    account_id = Column(String, index=True)\n    customer_name = Column(String)\n    amount = Column(Float)\n    timestamp = Column(DateTime, default=datetime.utcnow)\n    merchant_category = Column(String)\n    status = Column(String, default='PENDING')\n    \n    telemetry = relationship('TelemetryData', back_populates='transaction', uselist=False)\n    prediction = relationship('Prediction', back_populates='transaction', uselist=False)\n    decision = relationship('InvestigationDecision', back_populates='transaction', uselist=False)\n\nclass TelemetryData(Base):\n    __tablename__ = 'telemetry_data'\n    \n    id = Column(String, primary_key=True, default=generate_uuid)\n    transaction_id = Column(String, ForeignKey('transactions.id'))\n    \n    device_fingerprint = Column(String)\n    device_trust_score = Column(Float)\n    ip_address = Column(String)\n    ip_reputation = Column(String)\n    vpn_detected = Column(Boolean)\n    failed_logins = Column(Integer)\n    impossible_travel = Column(Boolean)\n    browser_changed = Column(Boolean)\n    powershell_execution = Column(Boolean)\n    endpoint_alert = Column(Boolean)\n    known_device = Column(Boolean)\n    session_risk = Column(Float)\n    velocity_score = Column(Float)\n    \n    transaction = relationship('Transaction', back_populates='telemetry')\n\nclass Prediction(Base):\n    __tablename__ = 'predictions'\n    \n    id = Column(String, primary_key=True, default=generate_uuid)\n    transaction_id = Column(String, ForeignKey('transactions.id'))\n    \n    fraud_probability = Column(Float)\n    confidence_score = Column(Float)\n    expected_prevented_loss = Column(Float)\n    recommendation = Column(String)\n    shap_top_features = Column(Text) # Stored as JSON string\n    natural_language_explanation = Column(Text)\n    \n    transaction = relationship('Transaction', back_populates='prediction')\n\nclass InvestigationDecision(Base):\n    __tablename__ = 'investigation_decisions'\n    \n    id = Column(String, primary_key=True, default=generate_uuid)\n    transaction_id = Column(String, ForeignKey('transactions.id'))\n    investigator_id = Column(String)\n    action_taken = Column(String)\n    notes = Column(Text)\n    created_at = Column(DateTime, default=datetime.utcnow)\n    \n    transaction = relationship('Transaction', back_populates='decision')\n",
    "app/schemas/__init__.py": "",
    "app/schemas/all_schemas.py": "from pydantic import BaseModel\nfrom typing import Optional, List, Dict, Any\nfrom datetime import datetime\n\nclass TelemetryDataBase(BaseModel):\n    device_fingerprint: str\n    device_trust_score: float\n    ip_address: str\n    ip_reputation: str\n    vpn_detected: bool\n    failed_logins: int\n    impossible_travel: bool\n    browser_changed: bool\n    powershell_execution: bool\n    endpoint_alert: bool\n    known_device: bool\n    session_risk: float\n    velocity_score: float\n\nclass TelemetryDataResponse(TelemetryDataBase):\n    id: str\n    transaction_id: str\n    class Config:\n        from_attributes = True\n\nclass PredictionBase(BaseModel):\n    fraud_probability: float\n    confidence_score: float\n    expected_prevented_loss: float\n    recommendation: str\n    shap_top_features: str\n    natural_language_explanation: str\n\nclass PredictionResponse(PredictionBase):\n    id: str\n    transaction_id: str\n    class Config:\n        from_attributes = True\n\nclass InvestigationDecisionBase(BaseModel):\n    action_taken: str\n    notes: str\n\nclass InvestigationDecisionCreate(InvestigationDecisionBase):\n    investigator_id: str\n\nclass InvestigationDecisionResponse(InvestigationDecisionBase):\n    id: str\n    transaction_id: str\n    investigator_id: str\n    created_at: datetime\n    class Config:\n        from_attributes = True\n\nclass TransactionBase(BaseModel):\n    account_id: str\n    customer_name: str\n    amount: float\n    merchant_category: str\n    status: str\n\nclass TransactionResponse(TransactionBase):\n    id: str\n    timestamp: datetime\n    class Config:\n        from_attributes = True\n\nclass TransactionDetailResponse(TransactionResponse):\n    telemetry: Optional[TelemetryDataResponse] = None\n    prediction: Optional[PredictionResponse] = None\n    decision: Optional[InvestigationDecisionResponse] = None\n"
}

for path, content in files.items():
    full_path = os.path.join(r"C:\Users\NEELS\Desktop\TeleFusion\decisionledger-tec\backend", path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w") as f:
        f.write(content)
print("Files generated successfully.")
